#### Ordinal Encoder

In [1]:
# apply on i/p Ordinal data 
import numpy as np
import pandas as pd

In [2]:
url = 'https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day26-ordinal-encoding/customer.csv'
df = pd.read_csv(url)

In [3]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [4]:
df = df.iloc[ : ,2: ]

In [5]:
df.sample(5)

     review education purchased
8   Average        UG        No
37  Average        PG       Yes
22     Poor        PG       Yes
28     Poor    School        No
14     Poor        PG       Yes

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test , y_train , y_test = train_test_split(df.iloc[ : ,0:2],df.iloc[ : ,-1],test_size=0.2,random_state=23)

In [7]:
x_train

     review education
29  Average        UG
10     Good        UG
44  Average        UG
3      Good        PG
22     Poor        PG
48     Good        UG
30  Average        UG
35     Poor    School
24  Average        PG
23     Good    School
4   Average        UG
42     Good        PG
7      Poor    School
1      Poor        UG
49     Good        UG
41     Good        PG
45     Poor        PG
15     Poor        UG
46     Poor        PG
16     Poor        UG
34  Average    School
37  Average        PG
0   Average    School
5   Average    School
21  Average        PG
11     Good        UG
2      Good        PG
43     Poor        PG
6      Good    School
25     Good    School
26     Poor        PG
39     Poor        PG
27     Poor        PG
12     Poor    School
31     Poor    School
47     Good        PG
9      Good        UG
40     Good    School
38     Good    School
19     Poor        PG

In [8]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder( categories=[['Poor','Average','Good'],['School','UG','PG']])

In [9]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [10]:
x_train_new=oe.transform(x_train)
x_test_new=oe.transform(x_test)

In [11]:
x_train_new

array([[1., 1.],
       [2., 1.],
       [1., 1.],
       [2., 2.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [0., 0.],
       [1., 2.],
       [2., 0.],
       [1., 1.],
       [2., 2.],
       [0., 0.],
       [0., 1.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [0., 1.],
       [0., 2.],
       [0., 1.],
       [1., 0.],
       [1., 2.],
       [1., 0.],
       [1., 0.],
       [1., 2.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [0., 0.],
       [2., 2.],
       [2., 1.],
       [2., 0.],
       [2., 0.],
       [0., 2.]])

#### Label Encoder

In [12]:
# apply on o/p ordinal data
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()

In [13]:
lb.fit(y_train)

LabelEncoder()

In [14]:
y_train=lb.transform(y_train)
y_test=lb.transform(y_test)

In [15]:
# order define autometically 
y_train

array([1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1])

In [16]:
lb.classes_

array(['No', 'Yes'], dtype=object)